Terrain
Czarodziejki/Czarodziejki-ze-Skaryszewa pull request #20
Opened 2024-11-11 17:36 UTC by ogoras

#15 #18

2024-11-12 20:35 UTC, simonsrz commented on Assets/BuildController.cs
> +
jak nie uzywamy to mozna by wywalic

2024-11-12 20:35 UTC, simonsrz requested changes
to co w komentarzu + duzo niepotrzebnych meta plikow i folderow

2024-11-15 12:44 UTC, ogoras commented on Assets/BuildController.cs
> +
done

2024-11-15 21:40 UTC, simonsrz approved these changes
lgtm

2024-11-15 21:53 UTC, merged